#!/bin/bash

# Generated for pending convergence runs with randomness 1 only.
# Includes rand1 jobs from submit_train.sh and submit_train_extra.sh.

# submit_train.sh
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_007_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_008_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_009_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_016_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_017_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_018_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_025_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_026_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_027_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_034_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_035_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_036_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_043_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_044_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_045_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_052_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_053_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_054_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_064_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_065_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_066_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_079_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_080_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_081_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_091_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_092_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_093_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_098_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_099_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_100_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_107_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_108_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_109_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_116_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_117_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_118_node15

# submit_train_extra.sh
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_013_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_014_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_015_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_028_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_029_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_030_rtx6000
