#!/bin/bash

# Submit replacements for pending CPU convergence jobs on node14/node15 CPUs.
# Intended after cancelling the old node03 CPU jobs.
# Uses 12 CPUs per task.
# Broader helper: submit_train.sh now contains only the currently running node03 CPU resubmission set.
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_045_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_052_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_053_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_064_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_065_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_066_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_092_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_093_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_098_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_099_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_100_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_116_node14
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_117_node15
sbatch slurm/slurm.sbatch_train_conv_remaining_cpu_118_node15
