#!/bin/bash

# Optional expensive convergence runs with randomness 0 or 1 only.
# q16 noisy runs execute on node03 RTX6000 GPUs with 16GB host RAM.
# q4/q8 noisy PSR runs execute on CPU nodes node14/node15.
# RTX6000 jobs may queue until the current GPU timing jobs finish.
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_001_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_002_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_003_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_013_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_014_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_015_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_016_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_017_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_018_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_028_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_029_rtx6000
sbatch slurm/slurm.sbatch_train_conv_remaining_gpu_q16_noisy_030_rtx6000
sbatch slurm/slurm.sbatch_psr_remaining_amp_q4_seed0_node14
sbatch slurm/slurm.sbatch_psr_remaining_amp_q4_seed1_node14
sbatch slurm/slurm.sbatch_psr_remaining_amp_q4_seed2_node14
sbatch slurm/slurm.sbatch_psr_remaining_ang_q4_seed0_node14
sbatch slurm/slurm.sbatch_psr_remaining_ang_q4_seed1_node15
sbatch slurm/slurm.sbatch_psr_remaining_ang_q4_seed2_node15
sbatch slurm/slurm.sbatch_psr_remaining_base_q4_seed0_node15
sbatch slurm/slurm.sbatch_psr_remaining_base_q4_seed1_node14
sbatch slurm/slurm.sbatch_psr_remaining_base_q4_seed2_node14
sbatch slurm/slurm.sbatch_psr_remaining_amp_q8_seed0_node14
sbatch slurm/slurm.sbatch_psr_remaining_amp_q8_seed1_node14
sbatch slurm/slurm.sbatch_psr_remaining_amp_q8_seed2_node15
sbatch slurm/slurm.sbatch_psr_remaining_ang_q8_seed0_node15
sbatch slurm/slurm.sbatch_psr_remaining_ang_q8_seed1_node15
sbatch slurm/slurm.sbatch_psr_remaining_ang_q8_seed2_node14
sbatch slurm/slurm.sbatch_psr_remaining_base_q8_seed0_node14
sbatch slurm/slurm.sbatch_psr_remaining_base_q8_seed1_node14
sbatch slurm/slurm.sbatch_psr_remaining_base_q8_seed2_node14
