#!/bin/bash

sbatch slurm/slurm.sbatch_cpu_train_conv_extra_impl_ang
sbatch slurm/slurm.sbatch_cpu_train_conv_extra_impl_amp
sbatch slurm/slurm.sbatch_gpu_train_conv_extra_noisy_psr_q4
sbatch slurm/slurm.sbatch_gpu_train_conv_extra_noisy_psr_q4_seed1
sbatch slurm/slurm.sbatch_gpu_train_conv_extra_noisy_psr_q4_seed2
sbatch slurm/slurm.sbatch_gpu_train_conv_extra_noisy_psr_q8
sbatch slurm/slurm.sbatch_gpu_train_conv_extra_noisy_psr_q8_seed1
sbatch slurm/slurm.sbatch_gpu_train_conv_extra_noisy_psr_q8_seed2
